# Generated by Django 4.0.3 on 2022-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger_tools', '0003_m_video_o_video_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_by_one', models.CharField(max_length=200, null=True)),
                ('on_by_many', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
