# Generated by Django 4.0.3 on 2022-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger_tools', '0006_remove_scale_on_with_many_remove_scale_on_with_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut_Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_merded', models.FileField(null=True, upload_to='cut_merged')),
            ],
        ),
    ]
