# Generated by Django 4.0.3 on 2022-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger_tools', '0013_delete_scale_alter_output_video_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='download_zip')),
            ],
        ),
        migrations.DeleteModel(
            name='Cut_Merged',
        ),
        migrations.DeleteModel(
            name='Cut_Original',
        ),
    ]
